### ISSUE TITLE
Fix Tribe Events Type Error

### ISSUE THREAD

**Issue by cyrillbolliger** [grueneschweiz/2018.gruene.ch#147]
```
[09-Feb-2022 05:20:13 UTC] PHP Fatal error:  Uncaught TypeError: Tribe\Events\Views\V2\Template\Page::set_hijacked_posts(): Argument #1 ($posts) must be of type array, SUPT\SUPTPostQuery given, called in /var/www/html/wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Template/Page.php on line 235 and defined in /var/www/html/wp-content/plugins/the-even
ts-calendar/src/Tribe/Views/V2/Template/Page.php:163
Stack trace:
#0 /var/www/html/wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Template/Page.php(235): Tribe\Events\Views\V2\Template\Page->set_hijacked_posts(Object(SUPT\SUPTPostQuery)
)
#1 /var/www/html/wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Hooks.php(200): Tribe\Events\Views\V2\Template\Page->maybe_hijack_main_query()
#2 /var/www/html/wp-includes/class-wp-hook.php(307): Tribe\Events\Views\V2\Hooks->on_wp_head('')
#3 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /var/www/html/wp-includes/general-template.php(3042): do_action('wp_head')
#6 [internal function]: wp_head()
#7 /var/www/html/wp-content/themes/les-verts/vendor/timber/timber/lib/Twig.php(296): call_user_func_array('wp_head', Array)
#8 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Environment.php(418) : eval()'d code(162): Timber\Twig->exec_function('wp_head')
#9 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(405): __TwigTemplate_90d1520a5c96bbe6e294ac5ffd55c4f797c332e24b23cd2ca40cfc829f44a41d->doDisplay(Array
, Array)
#10 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Environment.php(418) : eval()'d code(84): Twig\Template->display(Array)
#12 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(182): __TwigTemplate_fe2a8e956231c5b5ea0323db23707ac8a9963510e7eabe1991bd7d5e718a1437->block_html_hea
d_container(Array, Array)
#13 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Environment.php(418) : eval()'d code(41): Twig\Template->displayBlock('html_head_conta...', Array, Array)
#14 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(405): __TwigTemplate_fe2a8e956231c5b5ea0323db23707ac8a9963510e7eabe1991bd7d5e718a1437->doDisplay(Arra
y, Array)
#15 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Environment.php(418) : eval()'d code(47): Twig\Template->display(Array, Array)
#17 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(405): __TwigTemplate_decdfc15794b322e0b170396014bea2c4e83f6a987c64a3688c50b8a12c9555c->doDisplay(Arra
y, Array)
#18 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Environment.php(418) : eval()'d code(42): Twig\Template->display(Array, Array)
#20 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(405): __TwigTemplate_5dc1cb7e8428e7c2a302758fb96931bf299d3fd488b48b30035d4380a6b02f5c->doDisplay(Arra
y, Array)
#21 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#23 /var/www/html/wp-content/themes/les-verts/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#24 /var/www/html/wp-content/themes/les-verts/vendor/timber/timber/lib/Loader.php(79): Twig\TemplateWrapper->render(Array)
#25 /var/www/html/wp-content/themes/les-verts/vendor/timber/timber/lib/Timber.php(334): Timber\Loader->render('404.twig', Array, false, 'default')
#26 /var/www/html/wp-content/themes/les-verts/vendor/timber/timber/lib/Timber.php(383): Timber\Timber::compile('404.twig', Array, false, 'default', true)
#27 /var/www/html/wp-content/themes/les-verts/vendor/timber/timber/lib/Timber.php(410): Timber\Timber::fetch('404.twig', Array, false, 'default')
#28 /var/www/html/wp-content/themes/les-verts/404.php(24): Timber\Timber::render('404.twig', Array)
#29 /var/www/html/wp-includes/template-loader.php(106): include('/home/gruenewi/...')
#30 /var/www/html/wp-blog-header.php(19): require_once('/home/gruenewi/...')
#31 /var/www/html/index.php(17): require('/home/gruenewi/...')
#32 {main}
  thrown in /var/www/html/wp-content/plugins/the-events-calendar/src/Tribe/Views/V2/Template/Page.php on line 163
```

**Comment by sandrotanner** [comment]
evtl ein weitere error dieser Art: 

Hier https://github.com/grueneschweiz/2018.gruene.ch/blob/0f00fa8f8f3fab29c4c5879555dce6f37ab767b9/wordpress/wp-content/themes/les-verts/lib/timber/SUPTTribeEvent.php#L54 wird immer ein array von bis zu drei Strings erwartet, offenbar taucht oftmals ein array mit einem string und zwei weiteren arrays auf.

Hatte noch keine Zeit mir das genau anzuschauen, ein dirty hack wäre natürlich den beiden vorhergehenden ifs noch ein `is_string()` anzufügen

**Comment by sandrotanner** [comment]
@sandrotanner dominik informieren wenn gefixed

**Comment by cyrillbolliger** [comment]
> evtl ein weitere error dieser Art:
> 
> Hier
> 
> https://github.com/grueneschweiz/2018.gruene.ch/blob/0f00fa8f8f3fab29c4c5879555dce6f37ab767b9/wordpress/wp-content/themes/les-verts/lib/timber/SUPTTribeEvent.php#L54
> 
> wird immer ein array von bis zu drei Strings erwartet, offenbar taucht oftmals ein array mit einem string und zwei weiteren arrays auf.
> Hatte noch keine Zeit mir das genau anzuschauen, ein dirty hack wäre natürlich den beiden vorhergehenden ifs noch ein `is_string()` anzufügen

Vermutlich sind diese beiden Probleme unrelated. Aber letzteres wurde in 00c0a6de041f1ecf1753a94fe6cd04246bfc4a37 gefixed und dominik informiert.

**Comment by sandrotanner** [comment]
merci
